/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToursRouteImport } from './routes/tours'
import { Route as SemenRouteImport } from './routes/semen'
import { Route as KakhaRouteImport } from './routes/kakha'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CarsRouteImport } from './routes/cars'
import { Route as ArthurRouteImport } from './routes/arthur'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CarSlugRouteImport } from './routes/car.$slug'
import { Route as CalendarScopeRouteImport } from './routes/calendar.$scope'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminCarsRouteImport } from './routes/admin.cars'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'

const ToursRoute = ToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const SemenRoute = SemenRouteImport.update({
  id: '/semen',
  path: '/semen',
  getParentRoute: () => rootRouteImport,
} as any)
const KakhaRoute = KakhaRouteImport.update({
  id: '/kakha',
  path: '/kakha',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsRoute = CarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => rootRouteImport,
} as any)
const ArthurRoute = ArthurRouteImport.update({
  id: '/arthur',
  path: '/arthur',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CarSlugRoute = CarSlugRouteImport.update({
  id: '/car/$slug',
  path: '/car/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarScopeRoute = CalendarScopeRouteImport.update({
  id: '/calendar/$scope',
  path: '/calendar/$scope',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCarsRoute = AdminCarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/arthur': typeof ArthurRoute
  '/cars': typeof CarsRoute
  '/contact': typeof ContactRoute
  '/kakha': typeof KakhaRoute
  '/semen': typeof SemenRoute
  '/tours': typeof ToursRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/cars': typeof AdminCarsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/calendar/$scope': typeof CalendarScopeRoute
  '/car/$slug': typeof CarSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arthur': typeof ArthurRoute
  '/cars': typeof CarsRoute
  '/contact': typeof ContactRoute
  '/kakha': typeof KakhaRoute
  '/semen': typeof SemenRoute
  '/tours': typeof ToursRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/cars': typeof AdminCarsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/calendar/$scope': typeof CalendarScopeRoute
  '/car/$slug': typeof CarSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/arthur': typeof ArthurRoute
  '/cars': typeof CarsRoute
  '/contact': typeof ContactRoute
  '/kakha': typeof KakhaRoute
  '/semen': typeof SemenRoute
  '/tours': typeof ToursRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/cars': typeof AdminCarsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/calendar/$scope': typeof CalendarScopeRoute
  '/car/$slug': typeof CarSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/arthur'
    | '/cars'
    | '/contact'
    | '/kakha'
    | '/semen'
    | '/tours'
    | '/admin/calendar'
    | '/admin/cars'
    | '/admin/finance'
    | '/calendar/$scope'
    | '/car/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arthur'
    | '/cars'
    | '/contact'
    | '/kakha'
    | '/semen'
    | '/tours'
    | '/admin/calendar'
    | '/admin/cars'
    | '/admin/finance'
    | '/calendar/$scope'
    | '/car/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/arthur'
    | '/cars'
    | '/contact'
    | '/kakha'
    | '/semen'
    | '/tours'
    | '/admin/calendar'
    | '/admin/cars'
    | '/admin/finance'
    | '/calendar/$scope'
    | '/car/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArthurRoute: typeof ArthurRoute
  CarsRoute: typeof CarsRoute
  ContactRoute: typeof ContactRoute
  KakhaRoute: typeof KakhaRoute
  SemenRoute: typeof SemenRoute
  ToursRoute: typeof ToursRoute
  CalendarScopeRoute: typeof CalendarScopeRoute
  CarSlugRoute: typeof CarSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semen': {
      id: '/semen'
      path: '/semen'
      fullPath: '/semen'
      preLoaderRoute: typeof SemenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kakha': {
      id: '/kakha'
      path: '/kakha'
      fullPath: '/kakha'
      preLoaderRoute: typeof KakhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars': {
      id: '/cars'
      path: '/cars'
      fullPath: '/cars'
      preLoaderRoute: typeof CarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arthur': {
      id: '/arthur'
      path: '/arthur'
      fullPath: '/arthur'
      preLoaderRoute: typeof ArthurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/car/$slug': {
      id: '/car/$slug'
      path: '/car/$slug'
      fullPath: '/car/$slug'
      preLoaderRoute: typeof CarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/$scope': {
      id: '/calendar/$scope'
      path: '/calendar/$scope'
      fullPath: '/calendar/$scope'
      preLoaderRoute: typeof CalendarScopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cars': {
      id: '/admin/cars'
      path: '/cars'
      fullPath: '/admin/cars'
      preLoaderRoute: typeof AdminCarsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminCarsRoute: typeof AdminCarsRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCalendarRoute: AdminCalendarRoute,
  AdminCarsRoute: AdminCarsRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ArthurRoute: ArthurRoute,
  CarsRoute: CarsRoute,
  ContactRoute: ContactRoute,
  KakhaRoute: KakhaRoute,
  SemenRoute: SemenRoute,
  ToursRoute: ToursRoute,
  CalendarScopeRoute: CalendarScopeRoute,
  CarSlugRoute: CarSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
